### ISSUE TITLE
Possible better source of firmware

### ISSUE THREAD

**Issue by powpingdone** [kuruczgy/x1e-nixos-config#28]
https://github.com/anonymix007/x1e-firmware

This seems like a more complete source of firmware, containing not just the lenovo slim 7x firmware but also the asus and hp stuff.

**Comment by kuruczgy** [comment]
Do we have someone who could test this repo on those laptops?

**Comment by powpingdone** [comment]
You might be able to pop into the #aarch64-laptops irc and check with people there. You and I can only test the Lenovo stuff, unfortunately.

**Comment by kuruczgy** [comment]
My impression so far is that not many people there care about NixOS.

**Comment by powpingdone** [comment]
No, I mean like verifying with them that the firmware in that repo matches theirs.

**Comment by kuruczgy** [comment]
Ah, well, the firmware repo by anonymix007 was compiled in the first place by asking members of #aarch64-laptops to contribute theirs.

By "Do we have someone who could test this repo on those laptops?" I meant _my_ repo, e.g. I don't see much point in adding firmware for different laptops to this repo until someone can actually test if they can successfully install NixOS with it.

**Comment by kuruczgy** [comment]
Sorry, but I would prefer not to add stuff that we cannot test.

But I am hoping that eventually we will get a contributor here who is not on the yoga 7x, and as soon as someone can

1. test it,
2. preferably also confirm the hashes of the firmware files (so that we know they are consistent across machines),

then I am happy to add any firmware.
